#!/usr/bin/env python3
"""Generate 21 additional OCI training examples per category (71 x 21 = 1,491 total).

Uses 12 NEW response structures NOT in the existing 8 templates:
1. FAQ style (Q&A format)
2. Migration checklist
3. Cost optimization guide
4. Security hardening walkthrough
5. Performance tuning guide
6. Disaster recovery plan
7. Compliance checklist
8. Troubleshooting decision tree
9. Architecture comparison (2-3 options with pros/cons)
10. Step-by-step with screenshots description
11. API reference guide
12. Best practices with anti-patterns

Appends to existing data/curated/ files, then runs:
validate -> deduplicate -> split
"""

import json
import random
import sys
import subprocess
from pathlib import Path
from collections import Counter

random.seed(99)

# ============================================================================
# CONSTANTS - Same as generate_diverse_v2.py
# ============================================================================

SHAPES = [
    "VM.Standard.E4.Flex", "VM.Standard.A1.Flex", "VM.Optimized3.Flex",
    "BM.Standard.E5", "VM.GPU.A10.1", "VM.Standard3.Flex",
    "VM.Standard.E3.Flex", "BM.GPU4.8", "VM.DenseIO.E4.Flex",
]
REGIONS = [
    "sa-saopaulo-1", "us-ashburn-1", "us-phoenix-1", "eu-frankfurt-1",
    "uk-london-1", "ap-mumbai-1", "ap-tokyo-1", "ca-toronto-1",
    "ap-sydney-1", "me-jeddah-1",
]
COMPS = [
    "production", "development", "staging", "sandbox", "shared-services",
    "networking", "security", "data-platform", "analytics", "devops",
]
ADS = ["AD-1", "AD-2", "AD-3"]
OCPUS = [1, 2, 4, 8, 16, 32, 48, 64]
STORAGE_SIZES = [50, 100, 200, 500, 1000, 2000]
CIDRS = [
    "10.0.0.0/16", "10.1.0.0/16", "172.16.0.0/16", "192.168.0.0/16",
    "10.10.0.0/16", "10.20.0.0/16", "172.20.0.0/16", "192.168.10.0/24",
]
COMPANIES = [
    "NuvemTech Brasil", "DataPrime Solutions", "CloudBridge Inc",
    "FinOps Digital", "RetailPro Online", "MedSys Systems",
    "EduCloud Global", "TrackLog Logistics", "StreamMedia Pro",
    "AgroTech Innovations", "BankSecure Corp", "TripHub Platform",
    "CitySmart IoT", "PlayForge Studios", "Genomics Labs",
    "DriveAuto Systems", "PowerGrid Monitor", "SupplyChain Trace",
    "DocLegal Manager", "RiskTech Plus", "InfoSec Guardian",
    "WebScale Platform", "MicroServ Architecture", "DataLake Analytics",
    "NetOps Solutions",
]
PROJECTS = [
    "cloud-native-migration", "hybrid-infra-setup",
    "data-warehouse-modernization", "api-platform-launch",
    "iot-telemetry-pipeline", "ml-inference-deployment",
    "multi-tenant-saas", "real-time-streaming",
    "event-driven-architecture", "service-mesh-rollout",
    "observability-platform", "identity-management-upgrade",
    "backup-modernization", "network-automation",
    "container-orchestration", "database-migration-wave2",
    "cost-governance-program", "compliance-framework-v2",
    "edge-computing-pilot", "ai-ops-integration",
]

SYSTEM_PROMPTS = {
    "compute/instances": "You are an OCI specialist with expertise in Compute instances. Provide technical guidance on instance creation, shape selection, SSH access, and lifecycle management.",
    "compute/scaling": "You are an OCI specialist with expertise in Compute scaling. Provide technical guidance on instance pools, auto-scaling, and capacity planning.",
    "compute/custom-images": "You are an OCI specialist with expertise in Compute custom images. Provide technical guidance on custom image creation, boot volumes, and instance templates.",
    "storage/block": "You are an OCI specialist with expertise in Block Storage. Provide technical guidance on block volume creation, attachment, performance tiers, and backup strategies.",
    "storage/object": "You are an OCI specialist with expertise in Object Storage. Provide technical guidance on buckets, pre-authenticated requests, lifecycle policies, and versioning.",
    "storage/file": "You are an OCI specialist with expertise in File Storage. Provide technical guidance on NFS, mount targets, export options, and backup strategies.",
    "networking/vcn": "You are an OCI specialist with expertise in Virtual Cloud Networks. Provide technical guidance on VCN design, CIDR blocks, subnets, and gateways.",
    "networking/security": "You are an OCI specialist with expertise in network security. Provide technical guidance on Security Lists, Network Security Groups, and ingress/egress rules.",
    "networking/connectivity": "You are an OCI specialist with expertise in network connectivity. Provide technical guidance on DRG, VPN IPSec, FastConnect, and VCN peering.",
    "lb/load-balancer": "You are an OCI specialist with expertise in Load Balancing. Provide technical guidance on load balancer creation, backend sets, listeners, and health checks.",
    "database/autonomous": "You are an OCI specialist with expertise in Autonomous Database. Provide technical guidance on ATP, ADW, wallet management, and connection strings.",
    "database/mysql": "You are an OCI specialist with expertise in MySQL HeatWave. Provide technical guidance on MySQL configuration, scaling, and replication.",
    "database/postgresql": "You are an OCI specialist with expertise in OCI PostgreSQL. Provide technical guidance on instance management, scaling, and high availability.",
    "database/nosql": "You are an OCI specialist with expertise in Oracle NoSQL Database. Provide technical guidance on table creation, CRUD operations, and TTL.",
    "database/autonomous-json": "You are an OCI specialist with expertise in Autonomous JSON Database. Provide technical guidance on document store, MongoDB compatibility, and JSON collections.",
    "database/exadata": "You are an OCI specialist with expertise in Exadata Cloud Service. Provide technical guidance on infrastructure, DB systems, and patching.",
    "container/oke": "You are an OCI specialist with expertise in OKE. Provide technical guidance on cluster creation, node pools, and Kubernetes deployments.",
    "container/instances": "You are an OCI specialist with expertise in OCI Container Instances. Provide technical guidance on container deployment, OCIR, and image management.",
    "serverless/functions": "You are an OCI specialist with expertise in OCI Functions. Provide technical guidance on function deployment, invocation, and monitoring.",
    "serverless/api-gateway": "You are an OCI specialist with expertise in API Gateway. Provide technical guidance on routes, integrations, authentication, and throttling.",
    "security/iam-basics": "You are an OCI security specialist with expertise in IAM. Provide technical guidance on compartments, users, groups, and authentication.",
    "security/policies": "You are an OCI security specialist with expertise in IAM policies. Provide technical guidance on policy syntax, resource vs tenancy-level policies.",
    "security/dynamic-groups": "You are an OCI security specialist with expertise in Dynamic Groups. Provide technical guidance on dynamic group rules and instance principal.",
    "security/federation": "You are an OCI security specialist with expertise in federation. Provide technical guidance on IdCS, Okta, SAML, and OAuth.",
    "security/vault-secrets": "You are an OCI security specialist with expertise in Vault secrets. Provide technical guidance on secret creation, retrieval, and rotation.",
    "security/vault-keys": "You are an OCI security specialist with expertise in Vault keys. Provide technical guidance on key management, encryption, and key policies.",
    "security/encryption": "You are an OCI security specialist with expertise in encryption. Provide technical guidance on volume encryption, BYOK, and HSM integration.",
    "security/cloud-guard": "You are an OCI security specialist with expertise in Cloud Guard. Provide technical guidance on detector recipes and responder rules.",
    "security/waf": "You are an OCI security specialist with expertise in WAF. Provide technical guidance on Web Application Firewall, access rules, and rate limiting.",
    "migration/aws-compute": "You are an OCI specialist with expertise in AWS to OCI migration. Provide technical guidance on EC2 to Compute migration and shape mapping.",
    "migration/aws-storage": "You are an OCI specialist with expertise in AWS to OCI migration. Provide technical guidance on S3 to Object Storage migration.",
    "migration/aws-database": "You are an OCI specialist with expertise in AWS to OCI migration. Provide technical guidance on RDS to OCI Database migration.",
    "migration/azure-compute": "You are an OCI specialist with expertise in Azure to OCI migration. Provide technical guidance on Azure VMs to OCI Compute migration.",
    "migration/azure-storage": "You are an OCI specialist with expertise in Azure to OCI migration. Provide technical guidance on Azure Blob to Object Storage migration.",
    "migration/azure-database": "You are an OCI specialist with expertise in Azure to OCI migration. Provide technical guidance on Azure SQL to Autonomous Database migration.",
    "migration/gcp-compute": "You are an OCI specialist with expertise in GCP to OCI migration. Provide technical guidance on GCP Compute Engine to OCI Compute migration.",
    "migration/gcp-storage": "You are an OCI specialist with expertise in GCP to OCI migration. Provide technical guidance on GCP Cloud Storage to Object Storage migration.",
    "migration/gcp-database": "You are an OCI specialist with expertise in GCP to OCI migration. Provide technical guidance on GCP Cloud SQL to OCI Database migration.",
    "migration/onprem-compute": "You are an OCI specialist with expertise in on-premises to OCI migration. Provide technical guidance on lift-and-shift and cutover planning.",
    "migration/onprem-storage": "You are an OCI specialist with expertise in on-premises to OCI migration. Provide technical guidance on file storage and data transfer.",
    "migration/onprem-vmware": "You are an OCI specialist with expertise in VMware to OCI migration. Provide technical guidance on VMware Cloud Foundation and hybrid connectivity.",
    "migration/onprem-database": "You are an OCI specialist with expertise in on-premises to OCI migration. Provide technical guidance on Oracle to Autonomous Database migration.",
    "migration/data-transfer": "You are an OCI specialist with expertise in data transfer. Provide technical guidance on GoldenGate, Data Integration, and large-scale transfers.",
    "terraform/provider": "You are an OCI Terraform specialist. Provide technical guidance on provider configuration, authentication, and region setup.",
    "terraform/compute": "You are an OCI Terraform specialist. Provide technical guidance on Terraform resources for Compute, instance pools, and auto-scaling.",
    "terraform/storage": "You are an OCI Terraform specialist. Provide technical guidance on Terraform resources for Block Volume, Object Storage, and File Storage.",
    "terraform/networking": "You are an OCI Terraform specialist. Provide technical guidance on Terraform resources for VCN, subnets, and security configurations.",
    "terraform/load-balancer": "You are an OCI Terraform specialist. Provide technical guidance on Terraform resources for Load Balancer, backend sets, and listeners.",
    "terraform/database": "You are an OCI Terraform specialist. Provide technical guidance on Terraform resources for Autonomous Database, MySQL, and PostgreSQL.",
    "terraform/container": "You are an OCI Terraform specialist. Provide technical guidance on Terraform resources for OKE, node pools, and container instances.",
    "terraform/serverless": "You are an OCI Terraform specialist. Provide technical guidance on Terraform resources for Functions and API Gateway.",
    "terraform/security": "You are an OCI Terraform specialist. Provide technical guidance on Terraform resources for Vault, secrets, keys, and Cloud Guard.",
    "terraform/observability": "You are an OCI Terraform specialist. Provide technical guidance on Terraform resources for Logging, Monitoring, and Alarms.",
    "terraform/devops": "You are an OCI Terraform specialist. Provide technical guidance on Terraform resources for DevOps, artifacts, and Resource Manager.",
    "terraform/state": "You are an OCI Terraform specialist. Provide technical guidance on Terraform remote state, state locking, and workspaces.",
    "observability/logging": "You are an OCI specialist with expertise in Logging. Provide technical guidance on log groups, custom logs, and audit logs.",
    "observability/monitoring": "You are an OCI specialist with expertise in Monitoring. Provide technical guidance on metrics, alarms, and notifications.",
    "observability/stack-monitoring": "You are an OCI specialist with expertise in Stack Monitoring. Provide technical guidance on resource monitoring and database monitoring.",
    "observability/apm": "You are an OCI specialist with expertise in APM. Provide technical guidance on distributed tracing and performance diagnostics.",
    "troubleshooting/connectivity": "You are an OCI troubleshooting specialist with expertise in connectivity. Provide diagnostic guidance on routing, DNS, and VPN issues.",
    "troubleshooting/performance": "You are an OCI troubleshooting specialist with expertise in performance. Provide diagnostic guidance on CPU, memory, storage, and network performance.",
    "troubleshooting/authentication": "You are an OCI troubleshooting specialist with expertise in authentication. Provide diagnostic guidance on policy permissions and federation.",
    "troubleshooting/database": "You are an OCI troubleshooting specialist with expertise in database. Provide diagnostic guidance on connection issues and TNS errors.",
    "troubleshooting/compute": "You are an OCI troubleshooting specialist with expertise in Compute. Provide diagnostic guidance on provisioning, boot volume, and SSH issues.",
    "troubleshooting/storage": "You are an OCI troubleshooting specialist with expertise in storage. Provide diagnostic guidance on bucket access and performance issues.",
    "troubleshooting/oke": "You are an OCI troubleshooting specialist with expertise in OKE. Provide diagnostic guidance on cluster, node pool, and worker node issues.",
    "troubleshooting/functions": "You are an OCI troubleshooting specialist with expertise in Functions. Provide diagnostic guidance on function invocation and API Gateway errors.",
    "devops/ci-cd": "You are an OCI DevOps specialist. Provide technical guidance on build pipelines, deploy pipelines, and CI/CD automation.",
    "devops/resource-manager": "You are an OCI DevOps specialist. Provide technical guidance on Resource Manager Stacks, jobs, and drift detection.",
    "devops/artifacts": "You are an OCI DevOps specialist. Provide technical guidance on OCIR, artifacts service, and image management.",
    "devops/secrets": "You are an OCI DevOps specialist. Provide technical guidance on Vault secrets, pipeline secret injection, and rotation.",
}

DOC_LINKS = {
    "compute/instances": "https://docs.oracle.com/en-us/iaas/Content/Compute/Concepts/computeoverview.htm",
    "compute/scaling": "https://docs.oracle.com/en-us/iaas/Content/Compute/Concepts/computeoverview.htm",
    "compute/custom-images": "https://docs.oracle.com/en-us/iaas/Content/Compute/Tasks/managingcustomimages.htm",
    "storage/block": "https://docs.oracle.com/en-us/iaas/Content/Block/Concepts/blockvolumeperformance.htm",
    "storage/object": "https://docs.oracle.com/en-us/iaas/Content/Object/Concepts/objectstorageoverview.htm",
    "storage/file": "https://docs.oracle.com/en-us/iaas/Content/File/Concepts/filestorageoverview.htm",
    "networking/vcn": "https://docs.oracle.com/en-us/iaas/Content/Network/Concepts/overview.htm",
    "networking/security": "https://docs.oracle.com/en-us/iaas/Content/Network/Concepts/overview.htm",
    "networking/connectivity": "https://docs.oracle.com/en-us/iaas/Content/Network/Concepts/overview.htm",
    "lb/load-balancer": "https://docs.oracle.com/en-us/iaas/Content/LoadBalancing/Concepts/loadbalanceroverview.htm",
    "database/autonomous": "https://docs.oracle.com/en-us/iaas/Content/Database/Concepts/databaseoverview.htm",
    "database/mysql": "https://docs.oracle.com/en-us/iaas/Content/MySQL/Concepts/overview.htm",
    "database/postgresql": "https://docs.oracle.com/en-us/iaas/Content/Database/Concepts/databaseoverview.htm",
    "database/nosql": "https://docs.oracle.com/en-us/iaas/Content/NoSQL/Concepts/nosqloverview.htm",
    "database/autonomous-json": "https://docs.oracle.com/en-us/iaas/Content/Database/Concepts/databaseoverview.htm",
    "database/exadata": "https://docs.oracle.com/en-us/iaas/Content/Database/Concepts/databaseoverview.htm",
    "container/oke": "https://docs.oracle.com/en-us/iaas/Content/ContEng/Concepts/contengoverview.htm",
    "container/instances": "https://docs.oracle.com/en-us/iaas/Content/ContEng/Concepts/contengoverview.htm",
    "serverless/functions": "https://docs.oracle.com/en-us/iaas/Content/Functions/Concepts/functionsoverview.htm",
    "serverless/api-gateway": "https://docs.oracle.com/en-us/iaas/Content/ApiGateway/Concepts/apigatewayoverview.htm",
    "security/iam-basics": "https://docs.oracle.com/en-us/iaas/Content/Identity/Concepts/overview.htm",
    "security/policies": "https://docs.oracle.com/en-us/iaas/Content/Identity/Concepts/overview.htm",
    "security/dynamic-groups": "https://docs.oracle.com/en-us/iaas/Content/Identity/Concepts/overview.htm",
    "security/federation": "https://docs.oracle.com/en-us/iaas/Content/Identity/Concepts/overview.htm",
    "security/vault-secrets": "https://docs.oracle.com/en-us/iaas/Content/KeyManagement/Concepts/keyoverview.htm",
    "security/vault-keys": "https://docs.oracle.com/en-us/iaas/Content/KeyManagement/Concepts/keyoverview.htm",
    "security/encryption": "https://docs.oracle.com/en-us/iaas/Content/SecurityEncryption/overview.htm",
    "security/cloud-guard": "https://docs.oracle.com/en-us/iaas/Content/CloudGuard/concepts/cloudguardoverview.htm",
    "security/waf": "https://docs.oracle.com/en-us/iaas/Content/WAF/Concepts/overview.htm",
    "migration/aws-compute": "https://docs.oracle.com/en-us/iaas/Content/Migration/overview.htm",
    "migration/aws-storage": "https://docs.oracle.com/en-us/iaas/Content/Migration/overview.htm",
    "migration/aws-database": "https://docs.oracle.com/en-us/iaas/Content/Migration/overview.htm",
    "migration/azure-compute": "https://docs.oracle.com/en-us/iaas/Content/Migration/overview.htm",
    "migration/azure-storage": "https://docs.oracle.com/en-us/iaas/Content/Migration/overview.htm",
    "migration/azure-database": "https://docs.oracle.com/en-us/iaas/Content/Migration/overview.htm",
    "migration/gcp-compute": "https://docs.oracle.com/en-us/iaas/Content/Migration/overview.htm",
    "migration/gcp-storage": "https://docs.oracle.com/en-us/iaas/Content/Migration/overview.htm",
    "migration/gcp-database": "https://docs.oracle.com/en-us/iaas/Content/Migration/overview.htm",
    "migration/onprem-compute": "https://docs.oracle.com/en-us/iaas/Content/Migration/overview.htm",
    "migration/onprem-storage": "https://docs.oracle.com/en-us/iaas/Content/Storage/Concepts/storageoverview.htm",
    "migration/onprem-vmware": "https://docs.oracle.com/en-us/iaas/Content/cloud-migration/home.htm",
    "migration/onprem-database": "https://docs.oracle.com/en-us/iaas/Content/Migration/overview.htm",
    "migration/data-transfer": "https://docs.oracle.com/en-us/iaas/Content/Integration/overview.htm",
    "terraform/provider": "https://registry.terraform.io/providers/oracle/oci/latest/docs",
    "terraform/compute": "https://registry.terraform.io/providers/oracle/oci/latest/docs",
    "terraform/storage": "https://registry.terraform.io/providers/oracle/oci/latest/docs",
    "terraform/networking": "https://registry.terraform.io/providers/oracle/oci/latest/docs",
    "terraform/load-balancer": "https://registry.terraform.io/providers/oracle/oci/latest/docs",
    "terraform/database": "https://registry.terraform.io/providers/oracle/oci/latest/docs",
    "terraform/container": "https://registry.terraform.io/providers/oracle/oci/latest/docs",
    "terraform/serverless": "https://registry.terraform.io/providers/oracle/oci/latest/docs",
    "terraform/security": "https://registry.terraform.io/providers/oracle/oci/latest/docs",
    "terraform/observability": "https://registry.terraform.io/providers/oracle/oci/latest/docs",
    "terraform/devops": "https://registry.terraform.io/providers/oracle/oci/latest/docs",
    "terraform/state": "https://registry.terraform.io/providers/oracle/oci/latest/docs",
    "observability/logging": "https://docs.oracle.com/en-us/iaas/Content/Logging/overview.htm",
    "observability/monitoring": "https://docs.oracle.com/en-us/iaas/Content/Monitoring/overview.htm",
    "observability/stack-monitoring": "https://docs.oracle.com/en-us/iaas/Content/StackMonitoring/overview.htm",
    "observability/apm": "https://docs.oracle.com/en-us/iaas/Content/apm/overview.htm",
    "troubleshooting/connectivity": "https://docs.oracle.com/en/learn/oci-ntw-troubleshoot-1/index.html",
    "troubleshooting/performance": "https://docs.oracle.com/en-us/iaas/Content/Compute/Concepts/computeoverview.htm",
    "troubleshooting/authentication": "https://docs.oracle.com/en-us/iaas/Content/Identity/Concepts/overview.htm",
    "troubleshooting/database": "https://docs.oracle.com/en-us/iaas/Content/Database/Concepts/databaseoverview.htm",
    "troubleshooting/compute": "https://docs.oracle.com/en-us/iaas/Content/Compute/known-issues.htm",
    "troubleshooting/storage": "https://docs.oracle.com/en-us/iaas/Content/Storage/Concepts/storageoverview.htm",
    "troubleshooting/oke": "https://docs.oracle.com/en-us/iaas/Content/ContEng/Concepts/contengoverview.htm",
    "troubleshooting/functions": "https://docs.oracle.com/en-us/iaas/Content/Functions/Concepts/functionsoverview.htm",
    "devops/ci-cd": "https://docs.oracle.com/en-us/iaas/Content/DevOps/Concepts/devopsoverview.htm",
    "devops/resource-manager": "https://docs.oracle.com/en-us/iaas/Content/ResourceManager/Concepts/resourcemanager.htm",
    "devops/artifacts": "https://docs.oracle.com/en-us/iaas/Content/Artifacts/Concepts/artifactsoverview.htm",
    "devops/secrets": "https://docs.oracle.com/en-us/iaas/Content/KeyManagement/Concepts/keyoverview.htm",
}

# Lookup tables - same as generate_diverse_v2.py
OCI_CLI_COMMANDS = {
    "compute/instances": {"create": "oci compute instance launch", "list": "oci compute instance list", "get": "oci compute instance get", "update": "oci compute instance update", "delete": "oci compute instance terminate", "id_param": "--instance-id"},
    "compute/scaling": {"create": "oci autoscaling auto-scaling-configuration create", "list": "oci autoscaling auto-scaling-configuration list", "get": "oci autoscaling auto-scaling-configuration get", "update": "oci autoscaling auto-scaling-configuration update", "delete": "oci autoscaling auto-scaling-configuration delete", "id_param": "--auto-scaling-configuration-id"},
    "compute/custom-images": {"create": "oci compute image create", "list": "oci compute image list", "get": "oci compute image get", "delete": "oci compute image delete", "id_param": "--image-id"},
    "storage/block": {"create": "oci bv volume create", "list": "oci bv volume list", "get": "oci bv volume get", "update": "oci bv volume update", "delete": "oci bv volume delete", "id_param": "--volume-id"},
    "storage/object": {"create": "oci os bucket create", "list": "oci os bucket list", "get": "oci os bucket get", "update": "oci os bucket update", "delete": "oci os bucket delete", "id_param": "--bucket-name"},
    "storage/file": {"create": "oci fs file-system create", "list": "oci fs file-system list", "get": "oci fs file-system get", "update": "oci fs file-system update", "delete": "oci fs file-system delete", "id_param": "--file-system-id"},
    "networking/vcn": {"create": "oci network vcn create", "list": "oci network vcn list", "get": "oci network vcn get", "update": "oci network vcn update", "delete": "oci network vcn delete", "id_param": "--vcn-id"},
    "networking/security": {"create": "oci network security-list create", "list": "oci network security-list list", "get": "oci network security-list get", "update": "oci network security-list update", "delete": "oci network security-list delete", "id_param": "--security-list-id"},
    "networking/connectivity": {"create": "oci network drg create", "list": "oci network drg list", "get": "oci network drg get", "update": "oci network drg update", "delete": "oci network drg delete", "id_param": "--drg-id"},
    "lb/load-balancer": {"create": "oci lb load-balancer create", "list": "oci lb load-balancer list", "get": "oci lb load-balancer get", "update": "oci lb load-balancer update", "delete": "oci lb load-balancer delete", "id_param": "--load-balancer-id"},
    "database/autonomous": {"create": "oci db autonomous-database create", "list": "oci db autonomous-database list", "get": "oci db autonomous-database get", "update": "oci db autonomous-database update", "delete": "oci db autonomous-database delete", "id_param": "--autonomous-database-id"},
    "database/mysql": {"create": "oci mysql db-system create", "list": "oci mysql db-system list", "get": "oci mysql db-system get", "update": "oci mysql db-system update", "delete": "oci mysql db-system delete", "id_param": "--db-system-id"},
    "database/postgresql": {"create": "oci database db-system create", "list": "oci database db-system list", "get": "oci database db-system get", "update": "oci database db-system update", "delete": "oci database db-system delete", "id_param": "--db-system-id"},
    "database/nosql": {"create": "oci nosql table create", "list": "oci nosql table list", "get": "oci nosql table get", "update": "oci nosql table update", "delete": "oci nosql table delete", "id_param": "--table-name-or-id"},
    "database/autonomous-json": {"create": "oci db autonomous-database create", "list": "oci db autonomous-database list", "get": "oci db autonomous-database get", "update": "oci db autonomous-database update", "delete": "oci db autonomous-database delete", "id_param": "--autonomous-database-id"},
    "database/exadata": {"create": "oci db system create", "list": "oci db system list", "get": "oci db system get", "update": "oci db system update", "delete": "oci db system delete", "id_param": "--db-system-id"},
    "container/oke": {"create": "oci ce cluster create", "list": "oci ce cluster list", "get": "oci ce cluster get", "update": "oci ce cluster update", "delete": "oci ce cluster delete", "id_param": "--cluster-id"},
    "container/instances": {"create": "oci container-instance container-instance create", "list": "oci container-instance container-instance list", "get": "oci container-instance container-instance get", "update": "oci container-instance container-instance update", "delete": "oci container-instance container-instance delete", "id_param": "--container-instance-id"},
    "serverless/functions": {"create": "oci fn application create", "list": "oci fn application list", "get": "oci fn application get", "update": "oci fn application update", "delete": "oci fn application delete", "id_param": "--application-id"},
    "serverless/api-gateway": {"create": "oci api-gateway gateway create", "list": "oci api-gateway gateway list", "get": "oci api-gateway gateway get", "update": "oci api-gateway gateway update", "delete": "oci api-gateway gateway delete", "id_param": "--gateway-id"},
    "security/iam-basics": {"create": "oci iam compartment create", "list": "oci iam compartment list", "get": "oci iam user get", "update": "oci iam user update", "delete": "oci iam user delete", "id_param": "--compartment-id"},
    "security/policies": {"create": "oci iam policy create", "list": "oci iam policy list", "get": "oci iam policy get", "update": "oci iam policy update", "delete": "oci iam policy delete", "id_param": "--policy-id"},
    "security/dynamic-groups": {"create": "oci iam dynamic-group create", "list": "oci iam dynamic-group list", "get": "oci iam dynamic-group get", "update": "oci iam dynamic-group update", "delete": "oci iam dynamic-group delete", "id_param": "--dynamic-group-id"},
    "security/federation": {"create": "oci iam identity-provider create", "list": "oci iam identity-provider list", "get": "oci iam identity-provider get", "update": "oci iam identity-provider update", "delete": "oci iam identity-provider delete", "id_param": "--identity-provider-id"},
    "security/vault-secrets": {"create": "oci vault secret create", "list": "oci vault secret list", "get": "oci vault secret get", "delete": "oci vault secret schedule-secret-deletion", "id_param": "--secret-id"},
    "security/vault-keys": {"create": "oci kms key create", "list": "oci kms key list", "get": "oci kms key get", "update": "oci kms key update", "delete": "oci kms key schedule-key-deletion", "id_param": "--key-id"},
    "security/encryption": {"create": "oci kms key create", "list": "oci kms key list", "get": "oci kms key get", "id_param": "--key-id"},
    "security/cloud-guard": {"create": "oci cloud-guard target create", "list": "oci cloud-guard target list", "get": "oci cloud-guard target get", "update": "oci cloud-guard target update", "delete": "oci cloud-guard target delete", "id_param": "--target-id"},
    "security/waf": {"create": "oci waas waas-policy create", "list": "oci waas waas-policy list", "get": "oci waas waas-policy get", "update": "oci waas waas-policy update", "delete": "oci waas waas-policy delete", "id_param": "--waas-policy-id"},
    "observability/logging": {"create": "oci logging log-group create", "list": "oci logging log-group list", "get": "oci logging log-group get", "delete": "oci logging log-group delete", "id_param": "--log-group-id"},
    "observability/monitoring": {"create": "oci monitoring alarm create", "list": "oci monitoring alarm list", "get": "oci monitoring alarm get", "update": "oci monitoring alarm update", "delete": "oci monitoring alarm delete", "id_param": "--alarm-id"},
    "observability/stack-monitoring": {"create": "oci stack-monitoring target create", "list": "oci stack-monitoring target list", "get": "oci stack-monitoring target get", "update": "oci stack-monitoring target update", "delete": "oci stack-monitoring target delete", "id_param": "--target-id"},
    "observability/apm": {"create": "oci apm domain create", "list": "oci apm domain list", "get": "oci apm domain get", "update": "oci apm domain update", "delete": "oci apm domain delete", "id_param": "--apm-domain-id"},
    "devops/ci-cd": {"create": "oci devops project create", "list": "oci devops project list", "get": "oci devops project get", "update": "oci devops project update", "delete": "oci devops project delete", "id_param": "--project-id"},
    "devops/resource-manager": {"create": "oci resource-manager stack create", "list": "oci resource-manager stack list", "get": "oci resource-manager stack get", "update": "oci resource-manager stack update", "delete": "oci resource-manager stack delete", "id_param": "--stack-id"},
    "devops/artifacts": {"create": "oci artifacts container repository create", "list": "oci artifacts container repository list", "get": "oci artifacts container repository get", "update": "oci artifacts container repository update", "delete": "oci artifacts container repository delete", "id_param": "--repository-id"},
    "devops/secrets": {"create": "oci vault secret create", "list": "oci vault secret list", "get": "oci vault secret get", "delete": "oci vault secret schedule-secret-deletion", "id_param": "--secret-id"},
}

OCI_PYTHON_SDK = {
    "compute/instances": {"client": "oci.core.ComputeClient", "create_method": "launch_instance", "list_method": "list_instances", "get_method": "get_instance", "delete_method": "terminate_instance", "model": "oci.core.models.LaunchInstanceDetails"},
    "compute/scaling": {"client": "oci.autoscaling.AutoScalingClient", "create_method": "create_auto_scaling_configuration", "list_method": "list_auto_scaling_configurations", "get_method": "get_auto_scaling_configuration", "delete_method": "delete_auto_scaling_configuration", "model": "oci.autoscaling.models.CreateAutoScalingConfigurationDetails"},
    "compute/custom-images": {"client": "oci.core.ComputeClient", "create_method": "create_image", "list_method": "list_images", "get_method": "get_image", "delete_method": "delete_image", "model": "oci.core.models.CreateImageDetails"},
    "storage/block": {"client": "oci.core.BlockstorageClient", "create_method": "create_volume", "list_method": "list_volumes", "get_method": "get_volume", "update_method": "update_volume", "delete_method": "delete_volume", "model": "oci.core.models.CreateVolumeDetails"},
    "storage/object": {"client": "oci.object_storage.ObjectStorageClient", "create_method": "create_bucket", "list_method": "list_buckets", "get_method": "get_bucket", "update_method": "update_bucket", "delete_method": "delete_bucket", "model": "oci.object_storage.models.CreateBucketDetails"},
    "storage/file": {"client": "oci.file_storage.FileStorageClient", "create_method": "create_file_system", "list_method": "list_file_systems", "get_method": "get_file_system", "update_method": "update_file_system", "delete_method": "delete_file_system", "model": "oci.file_storage.models.CreateFileSystemDetails"},
    "networking/vcn": {"client": "oci.core.VirtualNetworkClient", "create_method": "create_vcn", "list_method": "list_vcns", "get_method": "get_vcn", "update_method": "update_vcn", "delete_method": "delete_vcn", "model": "oci.core.models.CreateVcnDetails"},
    "networking/security": {"client": "oci.core.VirtualNetworkClient", "create_method": "create_security_list", "list_method": "list_security_lists", "get_method": "get_security_list", "update_method": "update_security_list", "delete_method": "delete_security_list", "model": "oci.core.models.CreateSecurityListDetails"},
    "networking/connectivity": {"client": "oci.core.VirtualNetworkClient", "create_method": "create_drg", "list_method": "list_drgs", "get_method": "get_drg", "update_method": "update_drg", "delete_method": "delete_drg", "model": "oci.core.models.CreateDrgDetails"},
    "lb/load-balancer": {"client": "oci.load_balancer.LoadBalancerClient", "create_method": "create_load_balancer", "list_method": "list_load_balancers", "get_method": "get_load_balancer", "update_method": "update_load_balancer", "delete_method": "delete_load_balancer", "model": "oci.load_balancer.models.CreateLoadBalancerDetails"},
    "database/autonomous": {"client": "oci.database.DatabaseClient", "create_method": "create_autonomous_database", "list_method": "list_autonomous_databases", "get_method": "get_autonomous_database", "update_method": "update_autonomous_database", "delete_method": "delete_autonomous_database", "model": "oci.database.models.CreateAutonomousDatabaseDetails"},
    "database/mysql": {"client": "oci.mysql.DbSystemClient", "create_method": "create_db_system", "list_method": "list_db_systems", "get_method": "get_db_system", "update_method": "update_db_system", "delete_method": "delete_db_system", "model": "oci.mysql.models.CreateDbSystemDetails"},
    "database/postgresql": {"client": "oci.database.DatabaseClient", "create_method": "create_db_system", "list_method": "list_db_systems", "get_method": "get_db_system", "update_method": "update_db_system", "delete_method": "delete_db_system", "model": "oci.database.models.CreateDbSystemDetails"},
    "database/nosql": {"client": "oci.nosql.NosqlClient", "create_method": "create_table", "list_method": "list_tables", "get_method": "get_table", "update_method": "update_table", "delete_method": "delete_table", "model": "oci.nosql.models.CreateTableDetails"},
    "database/autonomous-json": {"client": "oci.database.DatabaseClient", "create_method": "create_autonomous_database", "list_method": "list_autonomous_databases", "get_method": "get_autonomous_database", "update_method": "update_autonomous_database", "delete_method": "delete_autonomous_database", "model": "oci.database.models.CreateAutonomousDatabaseDetails"},
    "database/exadata": {"client": "oci.database.DatabaseClient", "create_method": "create_db_system", "list_method": "list_db_systems", "get_method": "get_db_system", "update_method": "update_db_system", "delete_method": "delete_db_system", "model": "oci.database.models.CreateDbSystemDetails"},
    "container/oke": {"client": "oci.container_engine.ContainerEngineClient", "create_method": "create_cluster", "list_method": "list_clusters", "get_method": "get_cluster", "update_method": "update_cluster", "delete_method": "delete_cluster", "model": "oci.container_engine.models.CreateClusterDetails"},
    "container/instances": {"client": "oci.container_instances.ContainerInstanceClient", "create_method": "create_container_instance", "list_method": "list_container_instances", "get_method": "get_container_instance", "update_method": "update_container_instance", "delete_method": "delete_container_instance", "model": "oci.container_instances.models.CreateContainerInstanceDetails"},
    "serverless/functions": {"client": "oci.functions.FunctionsManagementClient", "create_method": "create_application", "list_method": "list_applications", "get_method": "get_application", "update_method": "update_application", "delete_method": "delete_application", "model": "oci.functions.models.CreateApplicationDetails"},
    "serverless/api-gateway": {"client": "oci.apigateway.GatewayClient", "create_method": "create_gateway", "list_method": "list_gateways", "get_method": "get_gateway", "update_method": "update_gateway", "delete_method": "delete_gateway", "model": "oci.apigateway.models.CreateGatewayDetails"},
    "security/iam-basics": {"client": "oci.identity.IdentityClient", "create_method": "create_compartment", "list_method": "list_compartments", "get_method": "get_user", "update_method": "update_user", "delete_method": "delete_user", "model": "oci.identity.models.CreateCompartmentDetails"},
    "security/policies": {"client": "oci.identity.IdentityClient", "create_method": "create_policy", "list_method": "list_policies", "get_method": "get_policy", "update_method": "update_policy", "delete_method": "delete_policy", "model": "oci.identity.models.CreatePolicyDetails"},
    "security/dynamic-groups": {"client": "oci.identity.IdentityClient", "create_method": "create_dynamic_group", "list_method": "list_dynamic_groups", "get_method": "get_dynamic_group", "update_method": "update_dynamic_group", "delete_method": "delete_dynamic_group", "model": "oci.identity.models.CreateDynamicGroupDetails"},
    "security/federation": {"client": "oci.identity.IdentityClient", "create_method": "create_identity_provider", "list_method": "list_identity_providers", "get_method": "get_identity_provider", "update_method": "update_identity_provider", "delete_method": "delete_identity_provider", "model": "oci.identity.models.CreateIdentityProviderDetails"},
    "security/vault-secrets": {"client": "oci.vault.VaultsClient", "create_method": "create_secret", "list_method": "list_secrets", "get_method": "get_secret", "delete_method": "schedule_secret_deletion", "model": "oci.vault.models.CreateSecretDetails"},
    "security/vault-keys": {"client": "oci.key_management.KmsManagementClient", "create_method": "create_key", "list_method": "list_keys", "get_method": "get_key", "update_method": "update_key", "delete_method": "schedule_key_deletion", "model": "oci.key_management.models.CreateKeyDetails"},
    "security/encryption": {"client": "oci.key_management.KmsManagementClient", "create_method": "create_key", "list_method": "list_keys", "get_method": "get_key", "model": "oci.key_management.models.CreateKeyDetails"},
    "security/cloud-guard": {"client": "oci.cloud_guard.CloudGuardClient", "create_method": "create_target", "list_method": "list_targets", "get_method": "get_target", "update_method": "update_target", "delete_method": "delete_target", "model": "oci.cloud_guard.models.CreateTargetDetails"},
    "security/waf": {"client": "oci.waas.WaasClient", "create_method": "create_waas_policy", "list_method": "list_waas_policies", "get_method": "get_waas_policy", "update_method": "update_waas_policy", "delete_method": "delete_waas_policy", "model": "oci.waas.models.CreateWaasPolicyDetails"},
    "observability/logging": {"client": "oci.logging.LoggingClient", "create_method": "create_log_group", "list_method": "list_log_groups", "get_method": "get_log_group", "delete_method": "delete_log_group", "model": "oci.logging.models.CreateLogGroupDetails"},
    "observability/monitoring": {"client": "oci.monitoring.MonitoringClient", "create_method": "create_alarm", "list_method": "list_alarms", "get_method": "get_alarm", "update_method": "update_alarm", "delete_method": "delete_alarm", "model": "oci.monitoring.models.CreateAlarmDetails"},
    "observability/stack-monitoring": {"client": "oci.stack_monitoring.StackMonitoringClient", "create_method": "create_target", "list_method": "list_targets", "get_method": "get_target", "update_method": "update_target", "delete_method": "delete_target", "model": "oci.stack_monitoring.models.CreateTargetDetails"},
    "observability/apm": {"client": "oci.apm_control_plane.ApmDomainClient", "create_method": "create_apm_domain", "list_method": "list_apm_domains", "get_method": "get_apm_domain", "update_method": "update_apm_domain", "delete_method": "delete_apm_domain", "model": "oci.apm_control_plane.models.CreateApmDomainDetails"},
    "devops/ci-cd": {"client": "oci.devops.DevopsClient", "create_method": "create_project", "list_method": "list_projects", "get_method": "get_project", "update_method": "update_project", "delete_method": "delete_project", "model": "oci.devops.models.CreateProjectDetails"},
    "devops/resource-manager": {"client": "oci.resource_manager.ResourceManagerClient", "create_method": "create_stack", "list_method": "list_stacks", "get_method": "get_stack", "update_method": "update_stack", "delete_method": "delete_stack", "model": "oci.resource_manager.models.CreateStackDetails"},
    "devops/artifacts": {"client": "oci.artifacts.ContainerRepositoryClient", "create_method": "create_container_repository", "list_method": "list_container_repositories", "get_method": "get_container_repository", "update_method": "update_container_repository", "delete_method": "delete_container_repository", "model": "oci.artifacts.models.CreateContainerRepositoryDetails"},
    "devops/secrets": {"client": "oci.vault.VaultsClient", "create_method": "create_secret", "list_method": "list_secrets", "get_method": "get_secret", "delete_method": "schedule_secret_deletion", "model": "oci.vault.models.CreateSecretDetails"},
}

OCI_TERRAFORM_RESOURCES = {
    "compute/instances": {"resource": "oci_core_instance", "data_source": "oci_core_instances"},
    "compute/scaling": {"resource": "oci_core_instance_pool", "data_source": "oci_core_instance_pools"},
    "compute/custom-images": {"resource": "oci_core_image", "data_source": "oci_core_images"},
    "storage/block": {"resource": "oci_core_volume", "data_source": "oci_core_volumes"},
    "storage/object": {"resource": "oci_objectstorage_bucket", "data_source": "oci_objectstorage_buckets"},
    "storage/file": {"resource": "oci_file_storage_file_system", "data_source": "oci_file_storage_file_systems"},
    "networking/vcn": {"resource": "oci_core_vcn", "data_source": "oci_core_vcns"},
    "networking/security": {"resource": "oci_core_security_list", "data_source": "oci_core_security_lists"},
    "networking/connectivity": {"resource": "oci_core_drg", "data_source": "oci_core_drgs"},
    "lb/load-balancer": {"resource": "oci_load_balancer_load_balancer", "data_source": "oci_load_balancer_load_balancers"},
    "database/autonomous": {"resource": "oci_database_autonomous_database", "data_source": "oci_database_autonomous_databases"},
    "database/mysql": {"resource": "oci_mysql_mysql_db_system", "data_source": "oci_mysql_mysql_db_systems"},
    "database/postgresql": {"resource": "oci_database_db_system", "data_source": "oci_database_db_systems"},
    "database/nosql": {"resource": "oci_nosql_table", "data_source": "oci_nosql_tables"},
    "database/autonomous-json": {"resource": "oci_database_autonomous_database", "data_source": "oci_database_autonomous_databases"},
    "database/exadata": {"resource": "oci_database_db_system", "data_source": "oci_database_db_systems"},
    "container/oke": {"resource": "oci_containerengine_cluster", "data_source": "oci_containerengine_clusters"},
    "container/instances": {"resource": "oci_container_instances_container_instance", "data_source": "oci_container_instances_container_instances"},
    "serverless/functions": {"resource": "oci_functions_application", "data_source": "oci_functions_applications"},
    "serverless/api-gateway": {"resource": "oci_api_gateway_gateway", "data_source": "oci_api_gateway_gateways"},
    "security/iam-basics": {"resource": "oci_identity_compartment", "data_source": "oci_identity_compartments"},
    "security/policies": {"resource": "oci_identity_policy", "data_source": "oci_identity_policies"},
    "security/dynamic-groups": {"resource": "oci_identity_dynamic_group", "data_source": "oci_identity_dynamic_groups"},
    "security/federation": {"resource": "oci_identity_identity_provider", "data_source": "oci_identity_identity_providers"},
    "security/vault-secrets": {"resource": "oci_vault_secret", "data_source": "oci_vault_secrets"},
    "security/vault-keys": {"resource": "oci_kms_key", "data_source": "oci_kms_keys"},
    "security/encryption": {"resource": "oci_kms_key", "data_source": "oci_kms_keys"},
    "security/cloud-guard": {"resource": "oci_cloud_guard_target", "data_source": "oci_cloud_guard_targets"},
    "security/waf": {"resource": "oci_waas_waas_policy", "data_source": "oci_waas_waas_policies"},
    "observability/logging": {"resource": "oci_logging_log_group", "data_source": "oci_logging_log_groups"},
    "observability/monitoring": {"resource": "oci_monitoring_alarm", "data_source": "oci_monitoring_alarms"},
    "observability/stack-monitoring": {"resource": "oci_stack_monitoring_target", "data_source": "oci_stack_monitoring_targets"},
    "observability/apm": {"resource": "oci_apm_apm_domain", "data_source": "oci_apm_apm_domains"},
    "devops/ci-cd": {"resource": "oci_devops_project", "data_source": "oci_devops_projects"},
    "devops/resource-manager": {"resource": "oci_resource_manager_stack", "data_source": "oci_resource_manager_stacks"},
    "devops/artifacts": {"resource": "oci_artifacts_container_repository", "data_source": "oci_artifacts_container_repositories"},
    "devops/secrets": {"resource": "oci_vault_secret", "data_source": "oci_vault_secrets"},
    "terraform/provider": {"resource": "oci_core_compartment", "data_source": "oci_core_compartments"},
    "terraform/compute": {"resource": "oci_core_instance", "data_source": "oci_core_instances"},
    "terraform/storage": {"resource": "oci_core_volume", "data_source": "oci_core_volumes"},
    "terraform/networking": {"resource": "oci_core_vcn", "data_source": "oci_core_vcns"},
    "terraform/load-balancer": {"resource": "oci_load_balancer_load_balancer", "data_source": "oci_load_balancer_load_balancers"},
    "terraform/database": {"resource": "oci_database_autonomous_database", "data_source": "oci_database_autonomous_databases"},
    "terraform/container": {"resource": "oci_containerengine_cluster", "data_source": "oci_containerengine_clusters"},
    "terraform/serverless": {"resource": "oci_functions_application", "data_source": "oci_functions_applications"},
    "terraform/security": {"resource": "oci_vault_secret", "data_source": "oci_vault_secrets"},
    "terraform/observability": {"resource": "oci_monitoring_alarm", "data_source": "oci_monitoring_alarms"},
    "terraform/devops": {"resource": "oci_devops_project", "data_source": "oci_devops_projects"},
    "terraform/state": {"resource": "oci_objectstorage_bucket", "data_source": "oci_objectstorage_buckets"},
    "troubleshooting/connectivity": {"resource": "oci_core_vcn", "data_source": "oci_core_vcns"},
    "troubleshooting/performance": {"resource": "oci_core_instance", "data_source": "oci_core_instances"},
    "troubleshooting/authentication": {"resource": "oci_identity_policy", "data_source": "oci_identity_policies"},
    "troubleshooting/database": {"resource": "oci_database_autonomous_database", "data_source": "oci_database_autonomous_databases"},
    "troubleshooting/compute": {"resource": "oci_core_instance", "data_source": "oci_core_instances"},
    "troubleshooting/storage": {"resource": "oci_core_volume", "data_source": "oci_core_volumes"},
    "troubleshooting/oke": {"resource": "oci_containerengine_cluster", "data_source": "oci_containerengine_clusters"},
    "troubleshooting/functions": {"resource": "oci_functions_application", "data_source": "oci_functions_applications"},
}

CATEGORY_ALIAS = {
    "terraform/provider": "compute/instances", "terraform/compute": "compute/instances",
    "terraform/storage": "storage/block", "terraform/networking": "networking/vcn",
    "terraform/load-balancer": "lb/load-balancer", "terraform/database": "database/autonomous",
    "terraform/container": "container/oke", "terraform/serverless": "serverless/functions",
    "terraform/security": "security/vault-secrets", "terraform/observability": "observability/monitoring",
    "terraform/devops": "devops/ci-cd", "terraform/state": "storage/object",
    "troubleshooting/connectivity": "networking/vcn", "troubleshooting/performance": "compute/instances",
    "troubleshooting/authentication": "security/iam-basics", "troubleshooting/database": "database/autonomous",
    "troubleshooting/compute": "compute/instances", "troubleshooting/storage": "storage/block",
    "troubleshooting/oke": "container/oke", "troubleshooting/functions": "serverless/functions",
    "migration/aws-compute": "compute/instances", "migration/aws-storage": "storage/object",
    "migration/aws-database": "database/autonomous", "migration/azure-compute": "compute/instances",
    "migration/azure-storage": "storage/object", "migration/azure-database": "database/autonomous",
    "migration/gcp-compute": "compute/instances", "migration/gcp-storage": "storage/object",
    "migration/gcp-database": "database/autonomous", "migration/onprem-compute": "compute/instances",
    "migration/onprem-storage": "storage/block", "migration/onprem-vmware": "compute/instances",
    "migration/onprem-database": "database/autonomous", "migration/data-transfer": "storage/object",
}
